
services:
  postgres:
    build:
      context: ./src/database
      dockerfile: Dockerfile.postgres
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    build:
      context: ./src/database
      dockerfile: Dockerfile.redis
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
    driver: local