import { Router } from "express";

import announcementRoutes from "./announcementRoutes";
import authRoutes from "./authRoutes";
import campaignRoutes from "./campaignRoutes";
import campaignSettingRoutes from "./campaignSettingRoutes";
import chatRoutes from "./chatRoutes";
import companyRoutes from "./companyRoutes";
import contactListItemRoutes from "./contactListItemRoutes";
import contactListRoutes from "./contactListRoutes";
import contactRoutes from "./contactRoutes";
import dashboardRoutes from "./dashboardRoutes";
import helpRoutes from "./helpRoutes";
import invoiceRoutes from "./invoicesRoutes";
import messageRoutes from "./messageRoutes";
import planRoutes from "./planRoutes";
import pwaRoutes from "./pwaRoutes";
import queueOptionRoutes from "./queueOptionRoutes";
import queueRoutes from "./queueRoutes";
import quickMessageRoutes from "./quickMessageRoutes";
import salerRoutes from "./salerRoute";
import scheduleRoutes from "./scheduleRoutes";
import settingRoutes from "./settingRoutes";
import subscriptionRoutes from "./subScriptionRoutes";
import tagRoutes from "./tagRoutes";
import ticketNoteRoutes from "./ticketNoteRoutes";
import ticketRoutes from "./ticketRoutes";
import ticketTagRoutes from "./ticketTagRoutes";
import ticketzOSSRoutes from "./ticketzOSSRoutes";
import userRoutes from "./userRoutes";
import versionRoutes from "./versionRoutes";
import whatsappRoutes from "./whatsappRoutes";
import whatsappSessionRoutes from "./whatsappSessionRoutes";
import transmissionListRoutes from "./transmissionListRoutes";
import transmissionContactRoutes from "./ transmissionContactRoutes";

const routes = Router();

routes.use(userRoutes);
routes.use("/auth", authRoutes);
routes.use(settingRoutes);
routes.use(contactRoutes);
routes.use(ticketRoutes);
routes.use(whatsappRoutes);
routes.use(messageRoutes);
routes.use(messageRoutes);
routes.use(whatsappSessionRoutes);
routes.use(queueRoutes);
routes.use(companyRoutes);
routes.use(planRoutes);
routes.use(ticketNoteRoutes);
routes.use(quickMessageRoutes);
routes.use(helpRoutes);
routes.use(dashboardRoutes);
routes.use(queueOptionRoutes);
routes.use(scheduleRoutes);
routes.use(tagRoutes);
routes.use(contactListRoutes);
routes.use(contactListItemRoutes);
routes.use(campaignRoutes);
routes.use(campaignSettingRoutes);
routes.use(announcementRoutes);
routes.use(chatRoutes);
routes.use(subscriptionRoutes);
routes.use(invoiceRoutes);
routes.use(ticketTagRoutes);
routes.use(pwaRoutes);
routes.use(versionRoutes);
routes.use(ticketzOSSRoutes);
routes.use(salerRoutes);
routes.use(transmissionListRoutes);
routes.use(transmissionContactRoutes);

export default routes;
